spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:file:./test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

tech:
  guyi:
    web:
      quick:
        response:
          exception:
            handler:
              enable: true
              stack-trace: true
        cors:
          enable: true